### PR TITLE
Creating REPL

### LINKED ISSUE #13: Create REPL for cosmwasm package
ideally something that can be started with `npx cosmwasm`

### PR DESCRIPTION
**Pull request by msteiner96**
Resolves #13 

This small addition should be enough to use `@cosmjs/cli` with `npx cosmwasm` after publishing it to NPM. Tested with `npx .` while being in the repo.

### CODE REVIEW

**Review by webmaster128 — COMMENTED** [review]
Beautiful.

I wonder how the binary would be called if you install the package though. E.g. if you have https://github.com/public-awesome/stargaze-tools/blob/main/package.json and they install `cosmwasm` instead of `@cosmjs/cli`. What would be the name for this part? https://github.com/public-awesome/stargaze-tools/blob/main/package.json#L22-L28

**Comment by msteiner96** [comment]
Did some research and it should look like : 

```json
{
  ...
  "scripts": {
    ...
    "account": "npx . --init scripts/account.ts --code 'process.exit(0)'",
    "minter": "npx . --init scripts/minter.ts --code 'process.exit(0)'",
    "mint": "npx . --init scripts/mint.ts --code 'process.exit(0)'",
    ...
    "batch-mint": "npx . --init scripts/mint-batch.ts --code 'process.exit(0)'",
    "whitelist": "npx . --init scripts/whitelist.ts --code 'process.exit(0)'",
    "load": "npx . --init scripts/load.ts",
    ...
  }
}
```

**Comment by webmaster128** [comment]
Starting `.` can only work in our repo, not when someone installs `cosmwasm` (otherwise it would be extremely confusing).

But maybe they can reference the dependency by package name as long as there is only one binary? I.e. `npm cosmwasm` would start the installed version, not download one?

**Comment by msteiner96** [comment]
Oh of course if you didn't install it it would be `npx cosmwasm ...` instead

**Comment by webmaster128** [comment]
How is the binary called in `./node_nodules/.bin` when the package is installed in a different package? I think it should have a helpful name that also works if there are 50 binaries installed.

**Comment by msteiner96** [comment]
> Executables
> 
> When in global mode, executables are linked into {prefix}/bin on Unix, or directly into {prefix} on Windows. Ensure that path is in your terminal's PATH environment to run them.
> 
> When in local mode, executables are linked into ./node_modules/.bin so that they can be made available to scripts run through npm. (For example, so that a test runner will be in the path when you run npm test.)

(https://docs.npmjs.com/cli/v7/configuring-npm/folders)


-> According to that doc, it should be .bin/cosmwasm

**Comment by webmaster128** [comment]
I found the missing piece here: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bin

Bildschirmfoto 2022-02-24 um 15 56 47

**Pull request merged**
